site.host=https://tedneward.github.io/Research

render.tags=true
render.sitemap=true
render.tagsindex=true

template.allpages.file=allpages.ftl
template.categorypage.file=categorypage.ftl
template.searchindex.file=searchindex.ftl
template.searchindex.extension=.json

default.status=published
default.type=page

img.path.update=true
img.path.prepend.host=true

markdown.extensions=HARDWRAPS,AUTOLINKS,FENCED_CODE_BLOCKS,DEFINITIONS,TABLES,FOOTNOTES
