site.host=http://localhost:8000

db.store=memory

render.tags=true
render.sitemap=true
render.tagsindex=true

template.allpages.file=allpages.ftl
template.categorypage.file=categorypage.ftl

default.status=published
default.type=page

img.path.update=true
img.path.prepend.host=true

markdown.extensions=HARDWRAPS,AUTOLINKS,FENCED_CODE_BLOCKS,DEFINITIONS,TABLES,FOOTNOTES
