site.host=http://localhost:8000

render.tags=true
render.sitemap=true
render.tagsindex=true

template.allpages.file=allpages.ftl
template.categorypage.file=categorypage.ftl
template.searchindex.file=searchindex.ftl

default.status=published
default.type=page

uri.noExtension=true
uri.noExtension.prefix=/

img.path.update=true
img.path.prepend.host=true

markdown.extensions=HARDWRAPS,AUTOLINKS,FENCED_CODE_BLOCKS,DEFINITIONS,TABLES,FOOTNOTES
