# This is a basic workflow to help you get started with Actions

name: Research Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v2.7.0

      # Set up the Java environment
      - name: Set up JDK 1.8
        uses: actions/setup-java@d202f5dbf7256730fb690ec59f6381f1c1e99d49  # v1.4.4
        with:
          java-version: 1.8

      # Kick off JBake and bake
      - uses: eskatos/gradle-command-action@d42b89ae1dc7ee62c9a86bb51b13fbd0c4cae5f4  # v1.3.3
        with:
          arguments: bake

      # Log in to Azure
      - name: Azure Login
        uses: azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a  # v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
      
      # Batch-upload the output/ contents
      - name: Azure CLI script
        uses: azure/CLI@b143de62e0cbf4cde59da2a04e7b9880c2e0c86a  # v1.0.9
        with:
          inlineScript: |
            az storage blob upload-batch --overwrite -s $GITHUB_WORKSPACE/build/output -d \$web --connection-string "DefaultEndpointsProtocol=https;AccountName=researchstorage;AccountKey=${{ secrets.AZURE_LICENSE_KEY }};EndpointSuffix=core.windows.net"
